### PR TITLE
AutoObsidian and HighwayTools bug fixes

### PR DESCRIPTION
**Pull request by theredstoner**
AutoObsidian:
- Properly detect when inventory is full and don't keep trying to keep mining enderchests if inventory is full
- Fix 2 race conditions that were preventing SearchShulker from working properly
- Clean up some bad code

HighwayTools:
- Punch the block below fire blocks to break the fire
- Remove wallsigns from ignoreblocks as this was causing it to get stuck in cases where the wallsign was attached to a block we needed to mine
- Don't register the HighwayTools baritone process on every tick, only do it if necessary
- Allow HighwayTools to unpause after using AutoEat

### CODE REVIEW

**Comment by natan515** [comment]
WOW, its amazing how much you do! Good work!

**Comment by natan515** [comment]
No, please don't remove the sign from ignore list, just try to fix the issue with them, and u should change so for unbreakable blocks like bedrock the bot won't try to mine if they are 1 y lvl below, but all the others ignore blocks that can be removed will be mines on 1 y lvl below.

**Comment by theredstoner** [comment]
> No, please don't remove the sign from ignore list, just try to fix the issue with them, and u should change so for unbreakable blocks like bedrock the bot won't try to mine if they are 1 y lvl below, but all the others ignore blocks that can be removed will be mines on 1 y lvl below.

Hmm. How do you suggest I fix the issue with wallsigns? For now I will use this fix at least in my own local jar because it has stopped the bot in a few occasions.

**Comment by Avanatiker** [comment]
Ty a lot <3

**Pull request merged**
