### PR TITLE
Just update the version

### PR DESCRIPTION
**Pull request by natan515**

### CODE REVIEW

**Comment by theredstoner** [comment]
I could be wrong but I think the version is the version of the mod, not the version of minecraft

**Comment by natan515** [comment]
Yes it is, and rn its incorrect

**Comment by natan515** [comment]
The 1.12.1 isn't the Minecraft version its kami blue version, 1is 2020 12 is the month and 1 is the day

**Comment by Avanatiker** [comment]
Ah nice why wasnt it changed in the first place?

**Pull request merged**
